name: storeapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animate_do: ^3.3.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.0.0
  get_it: ^7.2.0
  go_router: ^15.1.1
  json_serializable: ^6.9.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  
  shared_preferences: ^2.5.3
dev_dependencies:
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
# dart run build_runner build --delete-conflicting-outputs
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod

    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\english\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
