// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbgW5ailg3nGvFDUcj0URq-jff3cqKKJc',
    appId: '1:471703842999:web:c8dba3a051025d51699d32',
    messagingSenderId: '471703842999',
    projectId: 'storeapp-a08fe',
    authDomain: 'storeapp-a08fe.firebaseapp.com',
    storageBucket: 'storeapp-a08fe.firebasestorage.app',
    measurementId: 'G-LBZRPCD2W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6WOntF8vfPVC9ykOFR6o8YQC19Qc9f54',
    appId: '1:471703842999:android:56e41bf307da0429699d32',
    messagingSenderId: '471703842999',
    projectId: 'storeapp-a08fe',
    storageBucket: 'storeapp-a08fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXdgqLd2z8g92vMGsSkEyLkdJ7YK3-ns',
    appId: '1:471703842999:ios:433851c54b876dd7699d32',
    messagingSenderId: '471703842999',
    projectId: 'storeapp-a08fe',
    storageBucket: 'storeapp-a08fe.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXdgqLd2z8g92vMGsSkEyLkdJ7YK3-ns',
    appId: '1:471703842999:ios:433851c54b876dd7699d32',
    messagingSenderId: '471703842999',
    projectId: 'storeapp-a08fe',
    storageBucket: 'storeapp-a08fe.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbgW5ailg3nGvFDUcj0URq-jff3cqKKJc',
    appId: '1:471703842999:web:be6a1e3312139544699d32',
    messagingSenderId: '471703842999',
    projectId: 'storeapp-a08fe',
    authDomain: 'storeapp-a08fe.firebaseapp.com',
    storageBucket: 'storeapp-a08fe.firebasestorage.app',
    measurementId: 'G-2GXSC7ZX6N',
  );
}
